### ISSUE TITLE
Revamp the project, focus on e-books manipulation and creation

### ISSUE THREAD

**Issue by gaku-sei** [gaku-sei/dexter#27]
Over the time this repo went from a simple "script" to build cbz from images to a much more feature rich toolset.
The target is to move forward and provide more libraries and binaries to manipulate a broader set of _free_ file formats.

In order to achieve this, here are a list of tasks to tackle:
- [x] Drop [cbz-dexter-reindex](https://github.com/gaku-sei/dexter/tree/main/cbz-dexter-reindex) it's not needed anymore - https://github.com/gaku-sei/dexter/pull/30
- [x] Keep only [dexter](https://github.com/gaku-sei/dexter/tree/main/dexter), [sinister](https://github.com/gaku-sei/dexter/tree/main/sinister), and [dexter-core](https://github.com/gaku-sei/dexter/tree/main/dexter-core) in this repository - https://github.com/gaku-sei/dexter/pull/31
- [x] Create a new repo that will host the e-books related crates - https://github.com/gaku-sei/eco
- [x] Rename the crate eco-* to ease release and prepare the future work on epub, pdf, etc...
- [x] The [cbz wrapper around the zip crate](https://github.com/gaku-sei/eco/tree/main/eco-cbz) leaves to be desired. Let's work on it to offer a cleaner API - https://github.com/gaku-sei/eco/pull/1 https://github.com/gaku-sei/dexter/pull/33
- [ ] Support e-books creation for more formats (pdf, ebook, etc...) - dedicated issue: https://github.com/gaku-sei/eco/issues/5
- [ ] Support text based books creation and markdown (md to ebook, etc...) - dedicated issue: https://github.com/gaku-sei/eco/issues/6
- [ ] Publish the most stable crates to https://crates.io/ - dedicated issue: https://github.com/gaku-sei/eco/issues/7
- [ ] Polish the `eco-viewer` bin and add support for more formats - dedicated issue: https://github.com/gaku-sei/eco/issues/5

**Comment by gaku-sei** [comment]
Closing, the remaining tasks have their own issues opened on the dedicated repository https://github.com/gaku-sei/eco
